<Project>
  <PropertyGroup>
    <Version>1.1.0</Version>
    <Authors>Alexander Biemann</Authors>
    <Product>Project Tabletop</Product>
    <RepositoryUrl>https://github.com/abiemann/ProjectTabletop</RepositoryUrl>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>
</Project>
